package br.com.firstsoft.shapr.codegen.generators

import br.com.firstsoft.shapr.codegen.GeneratedFile
import br.com.firstsoft.shapr.dsl.*
import com.squareup.kotlinpoet.*

/**
 * Generates JPA entities for _locales tables following Payload's pattern.
 * Locales tables store localized field values with compound unique constraint on (_locale, _parent_id).
 */
class LocalesTableGenerator(private val basePackage: String) {
    
    private val entityPackage = "$basePackage.entity"
    
    private val entityAnnotation = ClassName("jakarta.persistence", "Entity")
    private val tableAnnotation = ClassName("jakarta.persistence", "Table")
    private val idAnnotation = ClassName("jakarta.persistence", "Id")
    private val generatedValueAnnotation = ClassName("jakarta.persistence", "GeneratedValue")
    private val generationTypeClass = ClassName("jakarta.persistence", "GenerationType")
    private val columnAnnotation = ClassName("jakarta.persistence", "Column")
    private val manyToOneAnnotation = ClassName("jakarta.persistence", "ManyToOne")
    private val joinColumnAnnotation = ClassName("jakarta.persistence", "JoinColumn")
    private val fetchTypeClass = ClassName("jakarta.persistence", "FetchType")
    private val uniqueConstraintAnnotation = ClassName("jakarta.persistence", "UniqueConstraint")
    private val instantClass = ClassName("java.time", "Instant")
    
    fun generate(collection: CollectionDefinition): GeneratedFile? {
        val localizedFields = collection.fields.filter { it.type.isLocalized() }
        if (localizedFields.isEmpty()) return null
        
        val parentClassName = slugToClassName(collection.slug)
        val className = "${parentClassName}Locale"
        val tableName = "${collection.slug}_locales"
        
        val classBuilder = TypeSpec.classBuilder(className)
            .addModifiers(KModifier.DATA)
            .addAnnotation(entityAnnotation)
            .addAnnotation(
                AnnotationSpec.builder(tableAnnotation)
                    .addMember("name = %S", tableName)
                    .addMember("uniqueConstraints = [%T(columnNames = [%S, %S])]",
                        uniqueConstraintAnnotation, "_locale", "_parent_id")
                    .build()
            )
        
        val constructorBuilder = FunSpec.constructorBuilder()
        
        // ID
        constructorBuilder.addParameter(ParameterSpec.builder("id", Long::class).defaultValue("0").build())
        classBuilder.addProperty(PropertySpec.builder("id", Long::class).initializer("id")
            .addAnnotation(idAnnotation)
            .addAnnotation(AnnotationSpec.builder(generatedValueAnnotation)
                .addMember("strategy = %T.IDENTITY", generationTypeClass).build())
            .build())
        
        // _locale
        constructorBuilder.addParameter(ParameterSpec.builder("locale", String::class).defaultValue("\"\"").build())
        classBuilder.addProperty(PropertySpec.builder("locale", String::class).initializer("locale")
            .addAnnotation(AnnotationSpec.builder(columnAnnotation)
                .addMember("name = %S", "_locale").addMember("nullable = false").addMember("length = 10").build())
            .build())
        
        // _parent relationship
        val parentType = ClassName(entityPackage, parentClassName).copy(nullable = true)
        constructorBuilder.addParameter(ParameterSpec.builder("parent", parentType).defaultValue("null").build())
        classBuilder.addProperty(PropertySpec.builder("parent", parentType).initializer("parent")
            .addAnnotation(AnnotationSpec.builder(manyToOneAnnotation)
                .addMember("fetch = %T.LAZY", fetchTypeClass).build())
            .addAnnotation(AnnotationSpec.builder(joinColumnAnnotation)
                .addMember("name = %S", "_parent_id").addMember("nullable = false").build())
            .build())
        
        // Add localized fields
        localizedFields.forEach { field -> addLocalizedField(field, constructorBuilder, classBuilder) }
        
        classBuilder.primaryConstructor(constructorBuilder.build())
        
        val file = FileSpec.builder(entityPackage, className)
            .addFileComment("Generated by Shapr CMS - DO NOT EDIT")
            .addType(classBuilder.build())
            .build()
        
        return GeneratedFile(entityPackage, className, file.toString())
    }
    
    private fun addLocalizedField(field: FieldDefinition, constructorBuilder: FunSpec.Builder, classBuilder: TypeSpec.Builder) {
        val name = field.name
        val type = field.type
        val kotlinType = String::class.asTypeName().copy(nullable = true)
        
        val colDef: String? = when (type) {
            is FieldType.Textarea, is FieldType.Code -> "TEXT"
            is FieldType.Json, is FieldType.RichText -> "JSONB"
            is FieldType.Point -> "geometry(Point,4326)"
            else -> null
        }
        
        val colType: TypeName = when (type) {
            is FieldType.Number -> if (type.integerOnly) Long::class.asTypeName().copy(nullable = true)
                                   else Double::class.asTypeName().copy(nullable = true)
            is FieldType.Checkbox -> Boolean::class.asTypeName().copy(nullable = true)
            is FieldType.Date -> instantClass.copy(nullable = true)
            else -> kotlinType
        }
        
        constructorBuilder.addParameter(ParameterSpec.builder(name, colType).defaultValue("null").build())
        
        val colBuilder = AnnotationSpec.builder(columnAnnotation).addMember("nullable = true")
        if (colDef != null) colBuilder.addMember("columnDefinition = %S", colDef)
        if (type is FieldType.Text) colBuilder.addMember("length = %L", type.maxLength)
        
        classBuilder.addProperty(PropertySpec.builder(name, colType).initializer(name)
            .addAnnotation(colBuilder.build()).build())
    }
}

