package br.com.firstsoft.shapr.codegen.generators

import br.com.firstsoft.shapr.codegen.GeneratedFile
import br.com.firstsoft.shapr.dsl.CollectionDefinition
import br.com.firstsoft.shapr.dsl.slugToClassName
import com.squareup.kotlinpoet.*
import com.squareup.kotlinpoet.ParameterizedTypeName.Companion.parameterizedBy

/**
 * Generates Spring Data JPA Repository interfaces using KotlinPoet.
 */
class RepositoryGenerator(private val basePackage: String) {
    
    private val entityPackage = "$basePackage.entity"
    private val repositoryPackage = "$basePackage.repository"
    
    private val jpaRepositoryClass = ClassName("org.springframework.data.jpa.repository", "JpaRepository")
    private val repositoryAnnotation = ClassName("org.springframework.stereotype", "Repository")
    
    fun generate(collection: CollectionDefinition): GeneratedFile {
        val entityClassName = slugToClassName(collection.slug)
        val repositoryName = "${entityClassName}Repository"
        
        val entityType = ClassName(entityPackage, entityClassName)
        val jpaRepositoryType = jpaRepositoryClass.parameterizedBy(entityType, Long::class.asTypeName())
        
        val interfaceSpec = TypeSpec.interfaceBuilder(repositoryName)
            .addSuperinterface(jpaRepositoryType)
            .addAnnotation(repositoryAnnotation)
            .build()
        
        val file = FileSpec.builder(repositoryPackage, repositoryName)
            .addFileComment("Generated by Shapr CMS - DO NOT EDIT")
            .addType(interfaceSpec)
            .build()
        
        return GeneratedFile(
            packageName = repositoryPackage,
            fileName = repositoryName,
            content = file.toString()
        )
    }
}
